spring.application.name=kronos

spring.datasource.url = jdbc:postgresql://localhost:5432/kronos
spring.datasource.username=postgres
spring.datasource.password=123456789
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always