spring.application.name=kronos

spring.datasource.url = jdbc:postgresql://207.246.115.107:5432/kronos
spring.datasource.username=appuser
spring.datasource.password=Kronos#2026!
#spring.datasource.url = jdbc:postgresql://localhost:5432/kronos
#spring.datasource.username=postgres
#spring.datasource.password=123

spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8081

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=masterkeysv04@gmail.com
spring.mail.password=bgwm uszf lrfs rjoc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

server.compression.enabled=false